services:
  - type: web
    name: frontend-tatwa
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://backend-mother-tatwa.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
